# Site settings
title: Grid Framework
tagline: Highly customizable responsive grid framework
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # use `jekyll serve --baseurl ''` in development
url: "http://www.gridframework.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
