# Site settings
title: Grid Framework
tagline: A highly customizable responsive grid framework
baseurl: "" # use `jekyll serve --baseurl ''` in development
url: "http://www.gridframework.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
