# Site settings
title: Grid Framework
tagline: A highly customizable responsive grid framework
baseurl: "/grid-framework" # use `jekyll serve --baseurl ''` in development
url: "http://mbillard.com/grid-framework" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
